name: Go CI Check

on:
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
          cache: false
      
      - name: Install Dependencies
        run: |
          go mod download
      
      - name: verify
        run: |
          go mod verify
      
      - name: Run Linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          # Optional: show only new issues if it's a pull request
          only-new-issues: true

      - name: Run Tests
        run: |
          make test
